# Workflow to connect to a runner
name: connect

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  build:
    name: build                        # Name of the job
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
    runs-on: ${{ matrix.os }}             # Operating system for the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build the JupyterLite site
        run: |
          cp README.md content
          jupyter lite build --contents content --output-dir dist

      - name: Setup tmate session (copy paste ssh command to connect to runner)   # Step to set up tmate session
        uses: mxschmitt/action-tmate@v3                                          # Use the action-tmate v3 action
